### ISSUE TITLE
Undefined variable: e

### ISSUE THREAD

**Issue by QadeerQT** [alchemyguy/YoutubeLaravelApi#10]
## Undefined variable: e
I'm getting this exception configuration is fine but still got this.
Can you tell me what is the solution to fix this?

![screenshot from 2019-03-05 15-38-27](https://user-images.githubusercontent.com/39376895/53800004-97a21100-3f5d-11e9-85ff-049a2024115a.png)

**Comment by alchemyguy** [comment]
@QadeerQT  I don't see any issue in the package that may be causing this issue. try using try-catch in your code for detailed exception
