### ISSUE TITLE
Fatal error when getting channel detail

### ISSUE THREAD

**Issue by adeel-arshad** [alchemyguy/YoutubeLaravelApi#11]
Hi, can you please help me with the following errors i m facing right now when trying to fetch channel details.

1- The user is not enabled for live streaming

Also i enabled live streaming option but then i was struck in this error

2- The user is blocked from live streaming.

Regards.
![1-live-streamning-not-enabled](https://user-images.githubusercontent.com/22236164/57685793-10a2a080-7652-11e9-8c81-271a1ff33786.png)
![2-user-blocked-from-streaming](https://user-images.githubusercontent.com/22236164/57685797-11d3cd80-7652-11e9-854e-a05119c7a11d.png)

**Comment by alchemyguy** [comment]
@adeel2188, it not the issue with the package seems youtube has put some restrictions on live streaming.
you can check if you are violating any of these restrictions
 - https://support.google.com/youtube/answer/2853834?hl=en
