### ISSUE TITLE
Array or Object? 

### ISSUE THREAD

**Issue by gelinger777** [alchemyguy/YoutubeLaravelApi#12]
```
##Auth-Token and Details For Channel
$authObject  = new AuthenticateService;
$authResponse = $authObject->authChannelWithCode($code);

```
You say in documentation that This will return an array. But it returns an object.

**Comment by alchemyguy** [comment]
@gelinger777  It seems to work as mentioned in documentation.
We are working on Upgrading the package to support Laravel 6/7, documentation will be updated in upcoming releases.
