### ISSUE TITLE
Compatibility with Laravel 7

### ISSUE THREAD

**Issue by lsfiege** [alchemyguy/YoutubeLaravelApi#13]
Hi! I was wondering if your package will add support for Laravel v6 and v7 :)

Greetings

**Comment by alchemyguy** [comment]
@lsfiege  Yes, I am working on support for Laravel v6/7.
It'll be upgraded soon in next release.

**Comment by bhagchandani** [comment]
Hi! is it supported by Laravel v6 ?

Thanks

**Comment by alchemyguy** [comment]
@bhagchandani  yes its supported by laravel 6.

**Comment by bhagchandani** [comment]
Hi @alchemyguy 
I am trying to install it via composer and current version of laravel is 6.2 in my project. but i am facing following problem.

> Problem 1
    - Installation request for sahusoftcom/youtube-livestream-api ^2.0 -> satisfiable by sahusoftcom/youtube-livestream-api[v2.0.0].
    - Conclusion: remove laravel/framework v6.18.14
    - Conclusion: don't install laravel/framework v6.18.14
    - sahusoftcom/youtube-livestream-api v2.0.0 requires laravel/framework ^5.1 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.18.14].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.18.14].
    - laravel/framework 5.2.x-dev conflicts with laravel/framework[v6.18.14].
    - laravel/framework 5.3.x-dev conflicts with laravel/framework[v6.18.14].
    - laravel/framework 5.4.x-dev conflicts with laravel/framework[v6.18.14].
    - laravel/framework 5.5.x-dev conflicts with laravel/framework[v6.18.14].
    - Can only install one of: laravel/framework[5.1.x-dev, v6.18.14].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.18.14].
    - Installation request for laravel/framework (locked at v6.18.14, required as ^6.2) -> satisfiable by laravel/framework[v6.18.14].

**Comment by alchemyguy** [comment]
@bhagchandani its not working with laravel 6 due because of laravel 5 dependency in the package, I'll work with
