### ISSUE TITLE
how to authenticate will you please sir give me some guidence how to use such package smoothly 

### ISSUE THREAD

**Issue by MusharafHabib** [alchemyguy/YoutubeLaravelApi#14]
what is the meaning of identifer in the function 
$authObject->getLoginUrl('email','identifier'); 
from where did i got those two variables 
$code = Input::get('code');
$identifier = Input::get('state');
please if you seen my issue please give me feedbcak about this 

thanks

**Comment by alchemyguy** [comment]
@MusharafHabib  

- Identifier is a `unique key` that you pass while creating a url and you'll get it back in redirect url, so that you can verify specific channel you are authorising.

- you get the same identifier data back in param called `state`.

just pass a unique value in identifier.
