### ISSUE TITLE
$streamStatus returns false

### ISSUE THREAD

**Issue by ssw10j** [alchemyguy/YoutubeLaravelApi#15]
event gets created
encoder starts sending live broadcast with zero dropped frames
but
$streamStatus = $ytEventObj->transitionEvent($authToken, $youtubeEventId, $broadcastStatus);
returns 'false' as boolean value.

Here's the code

```
$authToken = Session::get('authToken');
        $youtubeEventId = Session::get('youtubeEventId');
        $broadcastStatus="testing";

        $ytEventObj = new LiveStreamService();
        $streamStatus = $ytEventObj->transitionEvent($authToken, $youtubeEventId, $broadcastStatus);

        return response()->json($streamStatus);
```

Please let me know corrections if any

**Comment by alchemyguy** [comment]
@ssw10j  have you checked in your channel if the stream is being received ,at the time you are making this request from your app. I tested this and seems to be working fine for me.
