### ISSUE TITLE
Cannot use authChannelWithCode($code) if LiveStreaming is not enabled

### ISSUE THREAD

**Issue by Yasu-San** [alchemyguy/YoutubeLaravelApi#17]
## Detailed description

Using `authChannelWithCode($code)` on a channel with Live-Streaming disabled causes an Exception.

Example-Code:
```php
$ytAuth = new AuthenticateService();
dd($ytAuth->authChannelWithCode(Input::get('code')));
```

Exception (thrown in `vendor/alchemyguy/youtube-laravel-api/src/AuthenticateService.php:106`):
```
{ "error": { "code": 403, "message": "The user is blocked from live streaming.", "errors": [ { "message": "The user is blocked from live streaming.", "domain": "youtube.liveBroadcast", "reason": "livePermissionBlocked", "extendedHelp": "https://support.google.com/youtube/answer/2853834" } ] } } 
```

## Context

This prevents applications to receive the Auth-Codes for channels without the Live-Streaming-Feature being enabled.

## Your environment

* PHP 7.4
* Laravel 5.8
* Manjaro Linux 20.1

**Comment by alchemyguy** [comment]
@Yasu-San, sorry for late response, this is fixed in v1.0.1
