### ISSUE TITLE
Vendor publish conf is not working

### ISSUE THREAD

**Issue by milosb793** [alchemyguy/YoutubeLaravelApi#23]
Hey guys,

I've just installed the package and wanted to get the config using the command as is mentioned in readme: 
```
php artisan vendor:publish --tag='youtube-config'
```

but I'm getting the error: `Unable to locate publishable resources.`. 

Any idea about it?

**Comment by SwierczKacper** [comment]
I have same problem.

**Comment by alchemyguy** [comment]
@milosb793 @SwierczKacper  Sorry for the late response.

this is fixed in v1.0.3 of this package.
