### ISSUE TITLE
missing the required client identifier

### ISSUE THREAD

**Issue by pika15** [alchemyguy/YoutubeLaravelApi#29]
Hey, can anyone help me with this? I have an issue, where my program can't create login url, it seems missing client_id. I have double check on my env and my Google Console, and it's all good. It's work well on localhost, but when I upload it on my server, it's not work.

Exception:
![gambar](https://user-images.githubusercontent.com/44695170/117479862-0985a300-af8b-11eb-9b26-0e223472d92e.png)

Code on my controller:
`$authObject  = new AuthenticateService;`
`$authUrl = $authObject->getLoginUrl(auth()->user()->email);`

Thanks before~

**Comment by alchemyguy** [comment]
@Saiber99  have you updated the .env on your server. This error is thrown by google Auth SDK if client_id is missing in config.
I see same issue [here](https://github.com/alchemyguy/YoutubeLaravelApi/issues/9)

**Comment by pika15** [comment]
Yea, I've updated my .env on my server, I've tried dd (dump die) my .env on my server too and it's shown my updated client_id as well, but I don't know why when I tried to run this code, it always shows the error like that.

**Comment by pika15** [comment]
I've seen the previous issue you mentioned as well, and ofc, I do all steps you write on the documentation. Like I said before, it worked well on the localhost, but not on the server.

**Comment by pika15** [comment]
Hey! I fixed it!
So, it's because the default configuration on the `google-config.php` written in lowercase, but my google information on `.env` written in uppercase, I don't know why, but it's case sensitive on my server.

Before:
![gambar](https://user-images.githubusercontent.com/44695170/117535816-b579cd80-b021-11eb-87f7-72316cbbbd95.png)

After:
![gambar](https://user-images.githubusercontent.com/44695170/117535822-c32f5300-b021-11eb-972d-1f16c72d52c9.png)

Thanks @alchemyguy for trying to help me, I love your work, it's help me a lot!
