### ISSUE TITLE
Help me. 

### ISSUE THREAD

**Issue by khtodod** [alchemyguy/YoutubeLaravelApi#3]
Php code:
$channelServiceObject  = new ChannelService;
$mine = $channelServiceObject->subscriptionByChannelId($params = array('forChannelId'=>'UCk04n-A096jaFFwMhRL7dAA','mine'=>true));
 return $mine;

i got this error. 
"""
{\n
 "error": {\n
  "errors": [\n
   {\n
    "domain": "youtube.parameter",\n
    "reason": "authorizationRequired",\n
    "message": "The request uses the \u003ccode\u003emine\u003c/code\u003e parameter but is not properly authorized.",\n
    "locationType": "parameter",\n
    "location": "mine"\n
   }\n
  ],\n
  "code": 401,\n
  "message": "The request uses the \u003ccode\u003emine\u003c/code\u003e parameter but is not properly authorized."\n
 }\n
}\n
"""

**Comment by alchemyguy** [comment]
Hi,
this API request requires authorization to the channel. You can see your subscriptions only if you are authorized.

```php
$authObject = new AuthenticateService();
$loginUrl = $authObject->getLoginUrl($youtube_email);
\Log::info($loginUrl);

\\ by authorizing via the above this url get the auth code and replace the value of `$code` below
$response = $authObject->authChannelWithCode($code);
$token= $response['token'];
```

```php
$apiObject = new ChannelService;
$apiObject->setAccessToken($token);
\\ here in $resp will be your subscription details 
$resp = $apiObject->subscriptionByChannelId(array('mine' => true));
```
