### ISSUE TITLE
How to get google token to upload only in my youtube channel?

### ISSUE THREAD

**Issue by bocanhcam** [alchemyguy/YoutubeLaravelApi#32]
Hi, Thank you to creating this package.

I want to upload videos only in my channel so can I ignore the Oauth step to give the permission?.

I want people can upload videos directly to my channel.

**Comment by alchemyguy** [comment]
@bocanhcam 

You need to follow the steps [here](https://github.com/alchemyguy/YoutubeLaravelApi#google-auth) .
 
Generate **auth url** , visit it on browser and authorise your channel.
it will redirect you to your **website redirect url** with a `code` in params.

Now use this **code** to generate token as mentioned in [documentation](https://github.com/alchemyguy/YoutubeLaravelApi#google-auth) .
