### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by shanka12** [alchemyguy/YoutubeLaravelApi#4]
Could not find a matching version of package alchemyguy/YoutubeLaravelApi. Check the package spelling, your version constraint and that the package is available in a stability which matches your mini  
  mum-stability (stable).

laravel 5.4

**Comment by alchemyguy** [comment]
@shanka12 sorry for the inconvenience, the package name was updated recently.
please use:
composer require alchemyguy/youtube-laravel-api

**Comment by shanka12** [comment]
ok. Thanks
