### ISSUE TITLE
How can I attach a prerecorded video to the live stream

### ISSUE THREAD

**Issue by lamaji** [alchemyguy/YoutubeLaravelApi#7]
Thank you for this awesome package.
The broadcast function returns array of details from YouTube, good. 
But how can I use this info to start live stream using a pre-recorded video.
I don't see how to add a video on `transitionEvent()` function.

Please Help!

**Comment by anasmahjub1** [comment]
i have the same problem :(

**Comment by alchemyguy** [comment]
@anasmahjub1 @arradijamal sending stream is not a part of Youtube API V3. 
If you want me to build an encoder for it contact me via mail. 
mukesh201722@gmail.com

**Comment by anasmahjub1** [comment]
This means I must use an encryption program such as Wirecast ?!..

**Comment by alchemyguy** [comment]
It will require a separate module to be developed as it's not a part of
Youtube API,
If you want me to develop 1 for you please let me know,  With a proposal.
