### ISSUE TITLE
$googleToken Not Found

### ISSUE THREAD

**Issue by QadeerQT** [alchemyguy/YoutubeLaravelApi#8]
I'm trying to Upload the Video using Following Code but I can't see **$googleToken** where I can get this.

**Code:**
`$response = $videoServiceObject->uploadVideo($googleToken,
				$vdir.$vid_name, [
					'title'       => 'My Awesome Video',
					'description' => 'You can also specify your video description here.',
					'tags'	      => ['foo', 'bar', 'baz'],
					'category_id' => 10
				]
			);`

**Comment by alchemyguy** [comment]
Follow the steps to generate google auth token in the documentation [here](https://github.com/alchemyguy/YoutubeLaravelApi#google-auth)

**Comment by QadeerQT** [comment]
I got this exception...
**missing the required client identifier**
When doing this..

`$authObject  = new AuthenticateService;

		# Replace the identifier with a unqiue identifier for account or channel
		$authUrl = $authObject->getLoginUrl('qadeer.qt@gmail.com','UCC1YGOAVvZBM5d24jRGwSWw');`

**Comment by QadeerQT** [comment]
I don't see any **$googletoken variable in Auth process.**

**Comment by alchemyguy** [comment]
You get it in the response from 
```php
$authObject  = new AuthenticateService;
$authResponse = $authObject->authChannelWithCode($code);
```
then use, 
```php 
$googleToken = $authResponse['token'] 
```
there are few steps to generate auth token you need to follow them, you ***can't use token without generating it***.
GoogleToken is the auth token. Just follow the documentation properly.
